### PR TITLE
use standard fix

### PR DESCRIPTION
**Pull request by zeke**
This PR updates the test script to use `standard --fix`, which can clean up a lot of minor linting issues for you automatically.

### CODE REVIEW

**Comment by zeke** [comment]
> will it get corrected during the test run and not be reported as an error?

If the PR author didn't lint first, Yes. But it will come out in the wash. The next time someone lints locally, they'll commit the fixes.

**Comment by bkeepers** [comment]
Ehh, but then you'll have PRs that are modifying unrelated parts of the code base just to get the tests to pass.

**Comment by zeke** [comment]
Fair enough. Maybe we should add a `lint` script that's `standard --fix` for discoverability?

**Comment by bkeepers** [comment]
👍 want to give feedback on https://github.com/probot/template/pull/50 for that?

**Pull request closed without merging**
