### PR TITLE
npm script to lint code

### PR DESCRIPTION
**Pull request by itaditya**
It would improve the productivity of developers if they can fix their code to adher to standard guidelines by just writing `npm run format` or `yarn format`

### CODE REVIEW

**Comment by itaditya** [comment]
@zeke yes you're right, let me change that

**Comment by itaditya** [comment]
@zeke should I add something in the docs too ?

**Comment by zeke** [comment]
> should I add something in the docs too ?

Sure!

**Comment by itaditya** [comment]
@zeke made a PR https://github.com/probot/probot/pull/489 for the docs.

**Pull request merged**
